language: go

addons:
    postgresql: "9.3"

before_install:
  - go get code.google.com/p/go.tools/cmd/vet
  - go get github.com/golang/lint/golint

install:
  - go get -d -v -t ./...

before_script:
  - psql -c 'CREATE DATABASE travis;' -U postgres
  - psql travis < ./schema.sql

script:
  - go test ./...
  - go vet ./...
  - $HOME/gopath/bin/golint **/*.go
  - LINTED=$($HOME/gopath/bin/golint **/*.go| wc -l); if [ $LINTED -gt 0 ]; then echo "golint - $LINTED statements not up to spec, please run golint and follow the suggestions." && exit 1; fi
  - go build
  - source ./settings.travis && ./wireless_data_processor -all=true -dir=test_data/ -watch=false

after_script:
  - FIXED=$(go fmt ./... | wc -l); if [ $FIXED -gt 0 ]; then echo "gofmt - $FIXED file(s) not formatted correctly, please run gofmt to fix this." && exit 1; fi
